spring:
  application:
    name: product-manager
  data:
    mongodb:
      host: ds117691.mlab.com
      port: 17691
      database: k12x-dev
      username: vkum985
      password: vkum985

server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
  level:
    com:
      person:
        sam:
          product: INFO
    root: WARN
    org:
      springframework: WARN

ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 120000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
